In [0]:
# import PyTorch
import torch


In [0]:
# Write the Activation function (in this case sigmoid)
def activation(x):
  return 1/(1 + torch.exp(-x))

In [0]:
# Generate a seed to determine degree of randomness
torch.manual_seed(7)

# Use Pytorch randn to generate random normal distribution as a 1 by 5 matrix
features = torch.randn((1,5))

# Use rand_like to create another random matrix with the same size and shapes as features
weights = torch.randn_like(features)

# Create a bias with a randomly generated single value
bias = torch.randn((1,1))

print(features, weights, bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]]) tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]]) tensor([[0.3177]])


In [0]:
# Calculate the output of the neural network 
y = activation(torch.sum(features * weights) + bias)

In [0]:
print(y)

tensor([[0.1595]])


In [0]:
# We can also use PyTorch's matric multiplication function
y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

tensor([[0.1595]])
